###
# This is the place to override the deploy cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "deploy/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the deploy user and shell:
#
#normal[:cakephp][:core][:error_handler] = 'ErrorHandler::handleError'
#normal[:cakephp][:core][:exception_handler] = 'ErrorHandler::handleException'